-- Run this manually during deployment if an older Mazad database is missing
-- columns or support tables expected by the runtime APIs.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS birth_date DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS age INT(11) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS gender VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(30) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS profile_image LONGTEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS tokens INT(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS purchases_count INT(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sales_count INT(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rank_score INT(11) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rank_title VARCHAR(50) NOT NULL DEFAULT 'Bronze';

ALTER TABLE auctions
  ADD COLUMN IF NOT EXISTS winner_user_id INT(11) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS winner_bid_amount DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS settled_at DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS expected_final_price DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS max_acceptable_price DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS featured TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS category_showcase TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS showcase_order INT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS token_ledger (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  delta INT(11) NOT NULL,
  reason VARCHAR(191) DEFAULT NULL,
  auction_id INT(11) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY (user_id),
  KEY (auction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS auction_images (
  id INT(11) NOT NULL AUTO_INCREMENT,
  auction_id INT(11) NOT NULL,
  file_path VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  KEY (auction_id),
  CONSTRAINT fk_auction_images_auction FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS notifications (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) NOT NULL,
  type VARCHAR(50) DEFAULT 'info',
  subject VARCHAR(255) DEFAULT NULL,
  body TEXT,
  link VARCHAR(255) DEFAULT NULL,
  auction_id INT(11) DEFAULT NULL,
  is_read TINYINT(1) DEFAULT 0,
  sent_email TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY (user_id),
  KEY (auction_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
